#!/bin/bash
SRC="/Users/gosha/Desktop/демо генератор/тех задание ИИ фотосет"
DST="/Users/gosha/Desktop/демо генератор/ComfyUI/input"

cp "$SRC/test/референс.png" "$DST/референс.png"
cp "$SRC/test/референс 2.png" "$DST/референс_2.png"
cp "$SRC/Фоны (еще доработаются незначительно)/1 фон.jpg" "$DST/фон_1.jpg"
cp "$SRC/Фоны (еще доработаются незначительно)/фон 2.jpg" "$DST/фон_2.jpg"
cp "$SRC/Фоны (еще доработаются незначительно)/3 фон.jpg" "$DST/фон_3.jpg"
cp "$SRC/Фоны (еще доработаются незначительно)/4 фон.jpg" "$DST/фон_4.jpg"
cp "$SRC/test/ребенок фото1.JPG" "$DST/ребенок1.JPG"
cp "$SRC/test/ребенок фото 2.JPG" "$DST/ребенок2.JPG"
cp "$SRC/test/ребенок фото3.JPG" "$DST/ребенок3.JPG"
echo "All images copied to $DST"
ls "$DST"
